name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build # Replace this with the build command for your package

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # Make sure to create an NPM_AUTH_TOKEN secret in your repository containing your npmjs authentication token
